REQUIRE numbers.fs

CREATE LINE 80 ALLOT

CREATE ARRAY 25 CELLS 2* ALLOT
ARRAY 25 CELLS 2* ERASE

: .NUMBERS 0 DO DUP I CELLS 2* + 2@ D. LOOP DROP ;

: READLINE ( addr,l -- n )
  STDIN READ-LINE IF 2DROP 0 ELSE DROP THEN ;

LINE 80 READLINE .s cr DROP
LINE 80 ERASE
LINE 80 READLINE .s cr 
BYE
