REQUIRE ffl/tst.fs
REQUIRE set.fs
REQUIRE gossip.fs

." --- gossip ---" CR

T{ ." clear-stops -- driver-stop! -- stop@" CR
  CLEAR-STOPS
  0 4 DRIVER-STOP!
  7 4 DRIVER-STOP!
  4 STOP @ 10 SET-ITEMS 7 ?S 0 ?S
}T


T{ ." #drivers -- init-drivers -- driver" CR
  3 #DRIVERS !
  INIT-DRIVERS
  0 DRIVER @ 3 SET-ITEMS 0 ?S
  1 DRIVER @ 3 SET-ITEMS 1 ?S
  2 DRIVER @ 3 SET-ITEMS 2 ?S
}T

T{ ." drivers-at-stop -- gossip-at-stop -- gossip! -- complete" CR
  3 #DRIVERS !
  INIT-DRIVERS
  CLEAR-STOPS
  0 42 DRIVER-STOP!  1 42 DRIVER-STOP!
  42 DRIVERS-AT-STOP 3 SET-ITEMS 1 ?S 0 ?S
  42 GOSSIP-AT-STOP 3 SET-ITEMS 1 ?S 0 ?S
  42 GOSSIP!
  0 driver @ 3 set-items 1 ?s 0 ?s
  1 driver @ 3 set-items 1 ?s 0 ?s
  2 driver @ 3 set-items 2 ?s
  COMPLETE ?FALSE
  CLEAR-STOPS
  0 17 DRIVER-STOP!
  2 17 DRIVER-STOP!
  17 GOSSIP-AT-STOP 3 SET-ITEMS 2 ?S 1 ?S 0 ?S
  17 GOSSIP!
  0 DRIVER @ 3 SET-ITEMS 2 ?S 1 ?S 0 ?S
  1 DRIVER @ 3 SET-ITEMS 1 ?S 0 ?S
  2 DRIVER @ 3 SET-ITEMS 2 ?S 1 ?S 0 ?S
  CLEAR-STOPS
  0 23 DRIVER-STOP!
  1 23 DRIVER-STOP!
  23 GOSSIP!
  COMPLETE ?TRUE
}T

T{ ." length -- route -- minute-driver-stop" CR
  4 LENGTH ! 3 LENGTH CELL+ !
  42 0 0 DRIVER-MINUTE-ROUTE!  17 0 1 DRIVER-MINUTE-ROUTE!  23 0 2 DRIVER-MINUTE-ROUTE!  8 0 3 DRIVER-MINUTE-ROUTE!
  4807 1 0 DRIVER-MINUTE-ROUTE! 33 1 1 DRIVER-MINUTE-ROUTE! 1000 1 2 DRIVER-MINUTE-ROUTE!
  0 0 MINUTE-DRIVER-STOP 42 ?S
  1 0 MINUTE-DRIVER-STOP 17 ?S
  2 0 MINUTE-DRIVER-STOP 23 ?S
  3 0 MINUTE-DRIVER-STOP  8 ?S
  4 0 MINUTE-DRIVER-STOP 42 ?S
  5 0 MINUTE-DRIVER-STOP 17 ?S
  0 1 MINUTE-DRIVER-STOP 4807 ?S
  5 1 MINUTE-DRIVER-STOP 1000 ?S
  9 1 MINUTE-DRIVER-STOP 4807 ?S
}T
  
  
